// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace web_store_server.Domain.Models.Entities
{
    public partial class AuthRequest
    {
        public int Id { get; set; }
        public Guid ClientId { get; set; }
        public Guid UserId { get; set; }
        public string AccessToken { get; set; }
        public string RefreshToken { get; set; }
        public DateTimeOffset ExpireOn { get; set; }
        public DateTimeOffset CreatedAt { get; set; }

        public virtual AuthClient Client { get; set; }
        public virtual User User { get; set; }
    }
}