// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace web_store_server.Domain.Models.Entities
{
    public partial class Delivery
    {
        public Guid Id { get; set; }
        public int AddressId { get; set; }
        public int TypeId { get; set; }
        public Guid OrderId { get; set; }
        public DateTimeOffset EstimatedDeliveryDate { get; set; }
        public string Carrier { get; set; }
        public string TrackingNumber { get; set; }
        public long ShippingCost { get; set; }
        public int Status { get; set; }
        public DateTimeOffset CreatedAt { get; set; }

        public virtual CustomerAddress Address { get; set; }
        public virtual Order Order { get; set; }
        public virtual DeliveryType Type { get; set; }
    }
}