// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace web_store_server.Domain.Models.Entities
{
    public partial class PostGallery
    {
        public int Id { get; set; }
        public Guid PostId { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string MimeType { get; set; }
        public long Length { get; set; }
        public DateTimeOffset CreatedAt { get; set; }

        public virtual Post Post { get; set; }
    }
}