// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_store_server.Domain.Entities
{
    public partial class Coupon
    {
        public Coupon()
        {
            Sales = new HashSet<Sale>();
        }

        public Guid Id { get; set; }
        public string Code { get; set; }
        public int Discount { get; set; }
        public DateTimeOffset ExpireOn { get; set; }
        public DateTimeOffset CreatedAt { get; set; }

        public virtual ICollection<Sale> Sales { get; set; }
    }
}