// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_store_server.Domain.Entities
{
    public partial class CustomerAddress
    {
        public CustomerAddress()
        {
            Deliveries = new HashSet<Delivery>();
        }

        public int Id { get; set; }
        public Guid CustomerId { get; set; }
        public string Description { get; set; }
        public int Number { get; set; }
        public string AditionalInfo { get; set; }
        public bool Active { get; set; }
        public bool IsDeleted { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
        public DateTimeOffset? DeletedAt { get; set; }
        public DateTimeOffset? UpdatedAt { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual ICollection<Delivery> Deliveries { get; set; }
    }
}