// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_store_server.Domain.Entities
{
    public partial class OauthIdentityProvider
    {
        public OauthIdentityProvider()
        {
            UserOauthIdentities = new HashSet<UserOauthIdentity>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }

        public virtual ICollection<UserOauthIdentity> UserOauthIdentities { get; set; }
    }
}