// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_store_server.Domain.Entities
{
    public partial class OauthClient
    {
        public OauthClient()
        {
            UserOauthClientRequests = new HashSet<UserOauthClientRequest>();
        }

        public int Id { get; set; }
        public string ClientName { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string RedirectUri { get; set; }
        public DateTimeOffset CreatedAt { get; set; }

        public virtual ICollection<UserOauthClientRequest> UserOauthClientRequests { get; set; }
    }
}