// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_store_server.Domain.Entities
{
    public partial class Order
    {
        public Order()
        {
            Deliveries = new HashSet<Delivery>();
            Sales = new HashSet<Sale>();
        }

        public Guid Id { get; set; }
        public Guid CustomerId { get; set; }
        public string OrderNumber { get; set; }
        public int Status { get; set; }
        public DateTimeOffset CreatedAt { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual ICollection<Delivery> Deliveries { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}