// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_store_server.Domain.Entities
{
    public partial class Product
    {
        public Product()
        {
            ProductGalleries = new HashSet<ProductGallery>();
            ProductOffers = new HashSet<ProductOffer>();
            ProductSales = new HashSet<ProductSale>();
        }

        public Guid Id { get; set; }
        public int SubcategoryId { get; set; }
        public int BrandId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long Price { get; set; }
        public int Stock { get; set; }
        public string Sku { get; set; }
        public string Slug { get; set; }
        public List<string> Tags { get; set; }
        public bool Active { get; set; }
        public bool IsDeleted { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
        public DateTimeOffset? UpdatedAt { get; set; }
        public DateTimeOffset? DeletedAt { get; set; }

        public virtual ProductBrand Brand { get; set; }
        public virtual ProductSubcategory Subcategory { get; set; }
        public virtual ICollection<ProductGallery> ProductGalleries { get; set; }
        public virtual ICollection<ProductOffer> ProductOffers { get; set; }
        public virtual ICollection<ProductSale> ProductSales { get; set; }
    }
}