// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_store_server.Domain.Entities
{
    public partial class Sale
    {
        public Sale()
        {
            ProductSales = new HashSet<ProductSale>();
        }

        public Guid Id { get; set; }
        public Guid OrderId { get; set; }
        public long Total { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
        public DateTimeOffset? VirifiedAt { get; set; }

        public virtual Order Order { get; set; }
        public virtual ICollection<ProductSale> ProductSales { get; set; }
    }
}