// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace web_store_server.Domain.Models.Entities
{
    public partial class Sale
    {
        public Sale()
        {
            ProductSales = new HashSet<ProductSale>();
        }

        public Guid Id { get; set; }
        public Guid OrderId { get; set; }
        public Guid? CouponId { get; set; }
        public long Subtotal { get; set; }
        public long Total { get; set; }
        public int Status { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
        public DateTimeOffset? VirifiedAt { get; set; }

        public virtual Coupon Coupon { get; set; }
        public virtual Order Order { get; set; }
        public virtual ICollection<ProductSale> ProductSales { get; set; }
    }
}