// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_store_server.Domain.Entities
{
    public partial class UserOauthIdentity
    {
        public int Id { get; set; }
        public Guid UserId { get; set; }
        public Guid ProviderId { get; set; }
        public string AccountCode { get; set; }
        public string ProviderToken { get; set; }

        public virtual OauthIdentityProvider Provider { get; set; }
        public virtual User User { get; set; }
    }
}