// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace web_store_server.Domain.Entities
{
    public partial class UserOauthClientRequest
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Guid UserId { get; set; }
        public string AccessToken { get; set; }
        public string RefreshToken { get; set; }
        public bool? IsActive { get; set; }
        public DateTimeOffset ExpireOn { get; set; }
        public DateTimeOffset CreatedAt { get; set; }

        public virtual OauthClient Client { get; set; }
        public virtual User User { get; set; }
    }
}